// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyXIZleDSBwrbCjBQe7SaBrwNxw2P4_yo',
    appId: '1:588131930078:web:93dbc29f23e41c526dd74f',
    messagingSenderId: '588131930078',
    projectId: 'personal-drive-9a435',
    authDomain: 'personal-drive-9a435.firebaseapp.com',
    storageBucket: 'personal-drive-9a435.firebasestorage.app',
    measurementId: 'G-93MJRV4MCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClb4lpB3UTlCXimup8BvopRT9hi6r8mb4',
    appId: '1:588131930078:android:717d0bae50f0988b6dd74f',
    messagingSenderId: '588131930078',
    projectId: 'personal-drive-9a435',
    storageBucket: 'personal-drive-9a435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkVouGeAKUzXKPUT8mF0OgYLvm1w7bPCQ',
    appId: '1:588131930078:ios:68037ea0968758076dd74f',
    messagingSenderId: '588131930078',
    projectId: 'personal-drive-9a435',
    storageBucket: 'personal-drive-9a435.firebasestorage.app',
    iosClientId: '588131930078-hd7fch1aa2tjnm72f8uo6nrktbp58e2v.apps.googleusercontent.com',
    iosBundleId: 'com.personal-drive.app',
  );
}
